### ISSUE TITLE
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.The local variable vgg_img in the function read_vgg_img() in utils.py is referenced before assignment.

### ISSUE THREAD

**Issue by tlzhaoboling** [feiyanhu/FastSal#8]
I try to "predict using a image or a folder with images" according to the instruction on the website https://github.com/feiyanhu/FastSal, and get an error as pasted below. The local variable vgg_img in the function read_vgg_img() in utils.py is referenced before assignment. I wonder how this error can be solved? 
    Note that the python version (3.7) is not provided on the github, but is selected by myself.

(fsal) w@X299-WU8:/demo/w/00-ivc/FastSal$ python fastSal_predict.py -input_path image_examples -output_path image_examples
image folder is image_examples

Traceback (most recent call last):

  File "fastSal_predict.py", line 91, in <module>

    args.probability_output, args.batch_size, gpu=args.gpu)

  File "fastSal_predict.py", line 48, in predict

    for x, original_size_list, output_path_list in simple_loader:

  File "/home/w/anaconda3/envs/fsal/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__

    data = self._next_data()

  File "/home/w/anaconda3/envs/fsal/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data

    return self._process_data(data)

  File "/home/w/anaconda3/envs/fsal/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data

    data.reraise()

  File "/home/w/anaconda3/envs/fsal/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise

    raise self.exc_type(msg)

UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.

Original Traceback (most recent call last):

  File "/home/w/anaconda3/envs/fsal/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop

    data = fetcher.fetch(index)

  File "/home/w/anaconda3/envs/fsal/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch

    data = [self.dataset[idx] for idx in possibly_batched_index]

  File "/home/w/anaconda3/envs/fsal/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>

    data = [self.dataset[idx] for idx in possibly_batched_index]

  File "fastSal_predict.py", line 33, in __getitem__

    vgg_img, original_size = read_vgg_img(img_path, (192, 256))

  File "/demo/w/00-ivc/FastSal/dataset/utils.py", line 176, in read_vgg_img

    original_size = vgg_img.size

UnboundLocalError: local variable 'vgg_img' referenced before assignment

**Comment by feiyanhu** [comment]
Line 176 should be 'vgg_img = read_image(path, color=True)'. It's probably missing in your code.
